//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboracao
    {
        public long IdAnimador { get; set; }
        public int NrEvento { get; set; }
    
        public virtual Animador Animadores { get; set; }
        public virtual Evento Eventos { get; set; }
    }
}
